### ISSUE TITLE
When menu bar becomes smaller upon scrolling, logo is too small

### ISSUE THREAD

**Issue by afterwire** [afterwire/evidenceaction#1]
**Problem**
The logo in the top menu becomes too small to be usable when scrolling down the page. Currently the code sets it to be at 30% of its full width. Changing that value should fix the problem.

**Proposed solution**
Change the width from 30% to 50% like so

```css
body.scrolling header .elementor-691 
.elementor-element.elementor-element-68a2bd7 
.elementor-image img {
    width: 50% !important;
}
```

**Reference:**

Logo set at 30% width:
<img width="1289" alt="Screen Shot 2019-04-03 at 10 42 34 am" src="https://user-images.githubusercontent.com/46914245/55443135-49843a00-55fd-11e9-9763-36d8e39bcd04.png">

Logo set at 50% width:
<img width="1290" alt="Screen Shot 2019-04-03 at 10 42 57 am" src="https://user-images.githubusercontent.com/46914245/55443141-50ab4800-55fd-11e9-9bce-90022e4354e6.png">
