### ISSUE TITLE
Increase font size of blog post exerpts

### ISSUE THREAD

**Issue by afterwire** [afterwire/evidenceaction#20]
It is currently set to 14px can this be bumped up to 15px

```css
.elementor-posts .elementor-post__excerpt p {
    margin: 0;
    line-height: 1.5em;
    font-size: 15px;
    color: #777;
}
```
