### ISSUE TITLE
Inconsistent colors used across website

### ISSUE THREAD

**Issue by afterwire** [afterwire/evidenceaction#36]
With the colors that are used across the website it seems we have a few varieties at the moment.

I am not sure how the theme is setup and if you are using variables or not but just for clarification these are the correct values:

```css
:root {
  --main-pink-color: #fe6f87;
  --light-grey-color: #e8e5e2;
  --medium-grey-color: #a7a2a4;
  --dark-grey-color: #5e5f5f;
}
```

Some of the other values that we seem to be using at the moment include: 
`#646262` `#818a91` `#272727` `#ededed` `#54595f` `#929292` `#c9677c`
