### ISSUE TITLE
Decrease margin on homepage between program names and their icons

### ISSUE THREAD

**Issue by afterwire** [afterwire/evidenceaction#4]
**Issue:**
The gap between the program names and their icons on the homepage seems to be a bit much. 

**Existing example:**
<img width="936" alt="Screen Shot 2019-04-03 at 11 48 36 am" src="https://user-images.githubusercontent.com/46914245/55445339-93bde900-5606-11e9-8744-3cbe9b0e4200.png">

**Reduced Margin Example:**
<img width="916" alt="Screen Shot 2019-04-03 at 11 48 27 am" src="https://user-images.githubusercontent.com/46914245/55445352-9f111480-5606-11e9-82c4-4437b0cd56a6.png">

**Proposed solution:**

Reduce the `margin-top` value from `50px` to `30px`
```css
.elementor-654 .elementor-element.elementor-element-2992379 {
    margin-top: 50px;
    margin-bottom: 50px;
}
```
